### ISSUE TITLE
Export metrics

### ISSUE THREAD

**Issue by ablot** [flatironinstitute/mountainsort#11]
Hi,

I'd like to run mountainsort on a batch of mdas and save the output (non curated) firings.mda and the cluster metrics. What is the best way to export the cluster metrics? I've found them in the temp folder (`mountainlab/prvbucket/_mountainprocess/output_cluster_metrics_out_....`  but they don't seem to be exposed in the example pipeline (in `example_mlp`).
Should I modify the sort script to add metrics as an `outputs_opt ` or try to run the 3 `ms3.XX_metrics` processes after the sort?

**Comment by magland** [comment]
Yes, the example .mlp needs to be modified to output the metrics. Your two options are both good choices. The easiest would be to simply run the ms3 metrics stuff afterwards. Just make sure you are using the right pipelines.

And I should say that you should upgrade to the latest version of mlpipeline (if you haven't already) because the gui has improved in the last few days.

**Comment by ablot** [comment]
Thanks. It seems to work! 
While I'm here, a small feedback on the GUI. I have the last version of `mlpipeline` that apt returns (I cannot compare with the previous version, it's my first time using it). I haven't found how to change the input of the pipeline (in the `spec` field, not the inputs of the steps). In the end I noticed the  `Code view` switch and just edited the text there.
`mlp-larinet` complains when I try to click on the "Tree view":
`file:////usr/share/mlpipeline/web/mlpipeline/jsq/src/jsqcore/jquery-ui.min.js:22: TypeError: undefined is not an object (evaluating 'this._trackingInstances()[0]._focusTabbable')`
I have then an empty view. I can open a new issue if it is something that should work.

**Comment by magland** [comment]
Hi, I'd like to invite you to the slack group so we can discuss this in more detail. I'm creating docs now on how to deal with pipelines, and will answer some of your questions.

Could you send me an email so I know which email address to invite?
