### ISSUE TITLE
Geometry and Adjacency Radius

### ISSUE THREAD

**Issue by jstrohl** [flatironinstitute/mountainsort#13]
What would be an appropriate geometry and adjacency radius for a microwire tetrode? Would the following geom.csv work?
0,0
-25,25
25,25
0,50
And if this  is an appropriate geom.csv file, then what would the corresponding adjacency radius number be?
It seems to me the geom.csv should represent the position of each channel, but how do I relate this to an adjacency radius?

**Comment by magland** [comment]
adjacency_radius tells you which neighboring channels will be included in the neighborhood sorts. 

In your case, if you used the geom.csv that you typed, then if you used, for example, --adjacency_radius=3, each channel would be sorted separately. Use for example --adjacency_radius=100 to include all the channels in each neighborhood. Or you can use --adjacency_radius=-1 to also use all the channels in each sort.
