### ISSUE TITLE
Error when using "detect_sign":0

### ISSUE THREAD

**Issue by khl02007** [flatironinstitute/mountainsort#20]
Hi,

Thanks for making Mountainsort available to the community - we have just started testing it in our lab and it looks very promising! I wanted to report a small problem that I recently experienced: I get an error (see below) during the clustering step when I set "detect_sign" in my param.json to 0 (detect both upward and downward going spikes). When I set it to -1 (detect only downward going spikes), it runs fine with no errors. Any idea what the problem might be? The data is a silicon probe recording from a brain area where we previously found units with upward going spikes (based on other spike sorting algorithms like KiloSort), which is why we would like to detect both kinds of spikes. It is possible that the particular data set that I'm using contains no upward going spikes, but I'm not sure why that would cause an error rather than just return no cluster with upward gong average spike waveform.

Kyu

-------------------------------------------------------------------------------------------------------------------------------
  |mountainsortalg.ms3|            Sorting reduced clips 8x10x504717
  |mountainsortalg.ms3|            Sorted 384922 clips and found 2 clusters
  |mountainsortalg.ms3|            Sorted 522986 clips and found 3 clusters
  |mountainsortalg.ms3|            Consolidate. Keeping 384922 of 384922 events
  |mountainsortalg.ms3|            Dimension reduce clips 9x50x758340
  |mountainsortalg.ms3|            Dimension reduce clips 8x50x572311
  |mountainsortalg.ms3|            Dimension reduce clips 9x50x667471
  |mountainsortalg.ms3|            Consolidate. Keeping 456127 of 522986 events
  |mountainsortalg.ms3|            Sorting reduced clips 8x10x572311
  |mountainsortalg.ms3|            Sorted 504717 clips and found 2 clusters
  |mountainsortalg.ms3|            Sorting reduced clips 9x10x758340
  |mountainsortalg.ms3|            Sorting reduced clips 9x10x667471
  |mountainsortalg.ms3|            "Problem in isosplit5 while processing clips from: "
  |mountainsortalg.ms3|            "For debug purposes, writing clips to /tmp/debug_isosplit5_clips.mda and features to /tmp/debug_isosplit5_features.mda but note that the features are for a subset of the clips."
  |mountainsortalg.ms3|            Consolidate. Keeping 504717 of 504717 events
  |mountainsortalg.ms3|            Isosplit5 returned with an error. See above for debug information. Aborting
  |mountainsortalg.ms3|            DEBUG: iii[0]=0: -6.55998e-05 -3.6653e-05 2.31839e-05 -2.31814e-05 -7.46553e-06 1.97026e-05 2.8348e-05 -4.99605e-05 -4.11549e-05 3.02528e-05 
  |mountainsortalg.ms3|            DEBUG: iii[1]=1: -6.55998e-05 -3.6653e-05 2.31839e-05 -2.31814e-05 -7.46553e-06 1.97026e-05 2.8348e-05 -4.99605e-05 -4.11549e-05 3.02528e-05 
  |mountainsortalg.ms3|            DEBUG: iii[2]=2: 4.14992 -1.06447 1.68677 0.275393 -0.372508 0.778616 1.51219 -1.247 1.18937 -1.53657 
  |mountainsortalg.ms3|            Unexpected problem. New parcel has no points -- perhaps dataset contains duplicate points? -- original size = 17556.
  |mountainsortalg.ms3|            2018-01-15:21-58-34-685	mproc.main	warning	
  |mountainsortalg.ms3|            2018-01-15:21-58-34-916	mproc.main	warning	Process returned with non-zero exit code (6): mountainsortalg.ms3 (Elapsed: 1094.14 sec)
  |mountainsortalg.ms3|            making prv file: /hdd/tmp/mountainlab/prvbucket/_mountainprocess/output_console_out_e757cf8ffd.prv
Process error: 
Process error: 
Error in job (processor: mountainsortalg.ms3): Process error: 
Could not find input in running or pending jobs: firings_original_out
Error: Error in job (processor: mountainsortalg.ms3): Process error: 
Error: Error in job (processor: mountainsortalg.ms3): Process error: 
Stopped
Stopped

**Comment by magland** [comment]
Thanks for the bug report. This type of thing happened once before and it was found there was a bug with an older numpy, and the solution was

apt install python3-pip
pip3 install numpy

Otherwise... to best debug... how large is the dataset? (# channels, #timepoints, size on disk GB)

**Comment by khl02007** [comment]
Updating numpy seems to have fixed it. Thanks!

**Comment by magland** [comment]
Glad to hear.
