### ISSUE TITLE
PCA as a processor

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/mountainsort#23]
I see pca_unit_test() in pca.cpp but can't find a way to call it, and writing a MEX interface to pca is tricky due to the mda class. I would like to be able to run arbitrary tests on pca() from a high-level language with linear algebra.
One way to access PCA for easy testing would be to make it it's own processor. Then one could read/write mda files from octave to test it.

Also the term "sigma" in PCA doc usually means the singular value, not its square as you have it. This doesn't affect operation. 

Happy to be assigned these, although I've never made a new processor.

**Comment by magland** [comment]
This will happen at some future date.
