### ISSUE TITLE
document how to run unit tests

### ISSUE THREAD

**Issue by ahbarnett** [flatironinstitute/mountainsort#24]
Put in doc/ how to compile and run unit tests. Eg I found this works:

cd tests
qmake
make -j 8

tests/auto has subdirs w/ executables in it:

mountainlab/tests/auto/mlcompute/tst_mlcomputetest   .. all passed
 
But,  tst_mdatest has some fails. Just so you know.

**Comment by magland** [comment]
The tests directory no longer exists in the current mountainlab. I believe you were looking at the other (older) repo. With that said, we do need to implement unit testing system... it's on my list.
