### ISSUE TITLE
process descriptions

### ISSUE THREAD

**Issue by czawora** [flatironinstitute/mountainsort#27]
Hi,

I was wondering if there is any documentation that describes what most of the processes do? Often the names are quite apparent but a line or two for each would be useful. Specifically, what are the differences between the following: 

ms3.extract_clips
ms3.extract_firings
ms3.mv_extract_clips
ms3.mv_extract_clips_features
pyms.extract_clips

Thanks!

**Comment by magland** [comment]
We have a new capability:

mp-spec -h [processor name]
(will be published on the ppa in around 20 minutes)

Ultimately, somebody should make a took to generate the docs based on the specs.

enjoy
