### ISSUE TITLE
Mountainsort Parameters and Units.

### ISSUE THREAD

**Issue by baoloc10** [flatironinstitute/mountainsort#29]
Hi,

Is there documentations for each parameters in the mountainsort sorting algorithm? One that have 1 or 2 lines of description of each parameter and their units.  For example, what exactly is frequency width and is there a relationship between clip_size and detect-interval?

Similarly, What are does each parameters do (and what are their units) for the curation algorithm? For some reason, when running curation step, it filter out all spike data including what seems to be good spike data. I think it might be because the parameters for the curation algorithm may not match our lab's data.

Please direct me to the documentations.

Also, can I be added to the slack channel for future questions? 

Thank you.

**Comment by magland** [comment]
At some point we will have parameter docs that are more accessible. For now, you can do mp-spec on the individual processors in the pipeline to get information. (You'll need to read the script and see where the parameters get inserted, and then do mp-spec)

**Comment by baoloc10** [comment]
some of the mp-spec doesn't have parameters.

**Comment by magland** [comment]
Also, we have a new capability:
mp-spec -h [processor name]
