### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by gaelias** [flatironinstitute/mountainsort#30]
Hi,

This is probably more an issue with my limited (non-existent before now) understanding of Linux and running things via command line. Is there a way to set up batch processing with MountainSort? I have multiple days of recording sessions from multi-tetrode arrays where the tetrodes are driven semi-regularly between sessions so each days recordings are treated independently. Is there a way to set it up to automatically step through all the individual files without me having to run each file individually?

Thanks,
-gabe

**Comment by klaragerlei** [comment]
Hi,

I did this by writing a shell script. This will execute all these commands in this order, so they will all get sorted.

Best,
Klara


```
#!/bin/bash
echo "-----------------------------------------------------------------------------------"
echo "This is a shell script that will hopefully run mountain sort on all recordings in the folder."
echo "I am calling mountainsort now for tetrode 1, 2017-11-21_15-52-53."
mlp-run recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/mountainsort3.mlp sort --raw=recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/data/raw.mda --geom=recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/data/geom.csv --firings_out=recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/data/firings.mda --pre_out=recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/data/pre.mda --filt_out=recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/data/filt.mda --_params=recordings/2017-11-21_15-52-53/Electrophysiology/Spike_sorting/t1_2017-11-21_15-52-53_continuous/params.json
```

**Comment by gaelias** [comment]
Thanks! Total Linux novice. It seems like that's exactly what I need to do, thanks for pointing me in the right direction!
