### ISSUE TITLE
release python package for mdaio?

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/mountainsort#34]
I'd like to allow my python library to read mda files. It would be great to have mlpy on [PyPI](https://pypi.python.org/pypi) (apologies if I missed it! looks lik mlpy is a unrelated machine learning package).

Thanks for releasing mountainsort, and hope I'm not overwhelming with the issues made!

**Comment by magland** [comment]
Thanks for the suggestion. We will pursue this once the package has stabilized sufficiently.
