### ISSUE TITLE
std::bad_alloc

### ISSUE THREAD

**Issue by chengtang827** [flatironinstitute/mountainsort#36]
I have data from one channel, around 1 GB size. 
When I ran it in a 4 GB RAM Virtual Box, I got the **std::bad_alloc** error, so I segmented the whole data into four equal chunks with 1/4 GB each and sorted them one by one. 

But when I shift to a Linux machine with 16 GB RAM, I still get the **std::bad_alloc** error when running the 1 GB data, and I still have to break them into 1/4 GB segments.
So is this the issue of memory size? Why isn't the problem alleviated when I use larger memory?

**Comment by magland** [comment]
Could you please track the memory usage using a tool like top to determine whether it is running out of RAM. (I do admit that 1GB size is very small -- i don't expect it to run out of memory). Could you upload the dataset to our mlstudy web system? We can then test it there. Contact me by email for instructions on that.

**Comment by magland** [comment]
Closing, because this has been resolved. There was a bug that we fixed.
