### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by ulfschnabel** [flatironinstitute/mountainsort#4]
Hey guys,

thanks for making this available! I just followed your instructions on installation and ran into a small issue:

I installed mountainsort in a fresh Ubuntu VM. After following the steps described in your instructions I got an error message on the data synthesizing part of the example. Python told me that there is no module np.flip. Turns out I had to update numpy to the newest version, as the version that is installed when running the installation for mountainsort doesn't contain that function.

I hope this helps,

Cheers,

Ulf

**Comment by magland** [comment]
Thanks Ulf for the feedback. Just to clarify, did you use the Ubuntu packages? Or were you compiling from source?

**Comment by ulfschnabel** [comment]
I used the Ubuntu packages.

**Comment by magland** [comment]
Could you please do the following:
which python3

Trying to pinpoint the problem, and seeing if you have a different installation of python3 installed on your system (e.g., using conda), apart from what is installed by apt.

**Comment by czawora** [comment]
I also ran into this issue on a fresh Ubuntu VM. I solved it by running
sudo pip3 install --upgrade numpy
After that, the synthetic data generation worked

**Comment by magland** [comment]
I have to say I am surprised by this. I may replace that single line of code to avoid this issue in the future.
