### ISSUE TITLE
Docs are insufficient

### ISSUE THREAD

**Issue by agbondy** [flatironinstitute/mountainsort#41]
I'd be very interested in using MountainSort but I find the docs at https://mountainsort.readthedocs.io so incomplete as to make this impractical. Perhaps I'm missing a more complete set of documentation elsewhere?

**Comment by magland** [comment]
I agree, we need a reference manual. Right now the docs are meant to just be a getting started guide. Were you able to at least follow the instructions to install the software and then run the first example sorting? If so, I can help you with the next steps, answer your questions, and ideally be creating docs as we go.

**Comment by agbondy** [comment]
Thanks for the quick reply. No I haven't -- but I think some of my colleagues are going to give it a try.  They may get in touch.

**Comment by magland** [comment]
Okay. And FYI, there will be a new release in the coming weeks that will have much more thorough documentationn

**Comment by obaiam11** [comment]
Very excited for the new release! I have gotten the installation to work, as well as on my own data. I am having trouble getting the right geometrical coordinates, but sorting all channels independently works flawlessly. I am happy to be involved creating docs, as well as discuss what I'm using this for

**Comment by magland** [comment]
Okay, great. Please contact me by email.
