### ISSUE TITLE
Error in generating simulation data

### ISSUE THREAD

**Issue by sharlalka** [flatironinstitute/mountainsort#47]
![error](https://user-images.githubusercontent.com/39415802/40666290-f6d37440-6324-11e8-8860-03c861e522fd.PNG)

I am getting the following error when I am trying to run the simulation of data using "mlp-run synthesize_v1.mlp synthesize --timeseries=data/raw.mda --geom=data/geom.csv --waveforms_true=data/waveforms_true.mda --_params=params_synth.json" command. 

Please guide me through it.

**Comment by magland** [comment]
I am seeing the error "MemoryError". How much RAM do you have available on your system? Also, have you considered trying the newer version as explained in the README? mountainlab-js? There will be no more development on this particular repo.

**Comment by sharlalka** [comment]
I have 1GB of ram dedicated to it. Should I be allocating more to it? 

Recordings I have is from 4shank-32channels probe, and as discussed in the Read-me itself, it said it would be good for me to use this version as it has a well documented user manual. I can check that out too.
