### ISSUE TITLE
understanding bandpass process error

### ISSUE THREAD

**Issue by czawora** [flatironinstitute/mountainsort#5]
Hi,

I ran into an error when trying to sort my own data. I am attaching a screenshot. Is this a lack of memory error? I am trying to sort an mda file containing 8 channels from a utah array that lasts for about an hour. I currently have allocated 50GB of RAM to my ubuntu VM, is that insufficient in your experience?

Thanks
![screenshot 2017-11-28 13 17 24](https://user-images.githubusercontent.com/8885571/33336966-879443ee-d43f-11e7-93d5-4001bf067e49.png)

**Comment by jasonechung** [comment]
can you check if the tmp directory has sufficient space?

> du -sh /path/to/your/tmp
> df -h

**Comment by czawora** [comment]
seems there is space
![screenshot 2017-11-28 19 31 36](https://user-images.githubusercontent.com/8885571/33351654-d411b61a-d472-11e7-8be1-605d9b776934.png)

**Comment by czawora** [comment]
I suspect it's a problem with my mda file. Thanks for your help

**Comment by czawora** [comment]
I suspect it's an issue with my mda format. thanks for your help
