### ISSUE TITLE
Error with bandpass_filter in MountainSort3

### ISSUE THREAD

**Issue by cspurandare** [flatironinstitute/mountainsort#52]
I am using a virtualBox Ubuntu 16.04 with 4 Gb ram and 20GB harddisk space allotted. I have been following the installation and compilation steps for MountainSort and did not encounter any errors until the step of sorting example data. The error says

|ms3.bandpass_filter|      Error reading chunk 

The entire message is appended below

 |ms3.bandpass_filter|            RUNNING ms3.bandpass_filter: /home/chinmay/mountainlab/packages/mountainsort/packages/ms3/bin/ms3.mp ms3.bandpass_filter --timeseries=/home/chinmay/mountainsort_examples/examples/example1_mlp/data/raw.mda --timeseries_out=/tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_6af7fe0c7e --freq_max=6000 --freq_min=300 --freq_wid=1000 --quantization_unit=0 --samplerate=30000 --subsample_factor=1 --_tempdir=/tmp/mountainlab/tmp_short_term/tempdir_NKKSYC1TEI 
  |ms3.bandpass_filter|            Expected peak RAM usage (MB): 1024
  |ms3.bandpass_filter|            samplerate/freq_min/freq_max/freq_wid: 30000 300 6000 1000
  |ms3.bandpass_filter|            Error reading chunk
  |ms3.bandpass_filter|            Error reading chunk
  |ms3.bandpass_filter|            Error reading chunk
  |ms3.bandpass_filter|            Error reading chunk
  |ms3.bandpass_filter|            Error reading chunk
  |ms3.bandpass_filter|            ************+++ Using chunk size / overlap size: 4353924 / 0 (num threads=60000)
  |ms3.bandpass_filter|            Warning problem reading 2d chunk in DiskReadMda32: 0<>0
  |ms3.bandpass_filter|            4353924/0 (18000000%) -- using 0 threads.
  |ms3.bandpass_filter|            Warning problem reading 2d chunk in DiskReadMda32: 0<>0
  |ms3.bandpass_filter|            8707848/0 (18000000%) -- using 0 threads.
  |ms3.bandpass_filter|            Warning problem reading 2d chunk in DiskReadMda32: 0<>0
  |ms3.bandpass_filter|            13061772/0 (18000000%) -- using 0 threads.
  |ms3.bandpass_filter|            Warning problem reading 2d chunk in DiskReadMda32: 0<>0
  |ms3.bandpass_filter|            17415696/0 (18000000%) -- using 0 threads.
  |ms3.bandpass_filter|            Warning problem reading 2d chunk in DiskReadMda32: 0<>0
  |ms3.bandpass_filter|            18000000/0 (18000000%) -- using 0 threads.
  |ms3.bandpass_filter|            2018-06-13:17-05-01-479	mproc.main	warning	
  |ms3.bandpass_filter|            2018-06-13:17-05-01-498	mproc.main	warning	Process returned with non-zero exit code (255): ms3.bandpass_filter (Elapsed: 153.197 sec)
  |ms3.bandpass_filter|            making prv file: /tmp/mountainlab/prvbucket/_mountainprocess/output_console_out_6af7fe0c7e.prv
  |ms3.bandpass_filter|            making prv file: /tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_6af7fe0c7e.prv
Process error: 
Process error: 
Error in job (processor: ms3.bandpass_filter): Process error: 
Could not find input in running or pending jobs: filt_out
Error: Error in job (processor: ms3.bandpass_filter): Process error: 
Error: Error in job (processor: ms3.bandpass_filter): Process error: 
Stopped
Stopped
Stopped
Stopped

----------------------------------------XXX--------

Please let me know if any further information is needed. I have installed mountainlab-js but am a little lost about how the run the examples there. 
Thanks in advance,
Chinmay

**Comment by magland** [comment]
Perhaps you are running out of disk space in the /tmp directory?

**Comment by cspurandare** [comment]
Hi,
Yes you were right, it was a space issue. I ran the example by generating data for 60 instead of 600 seconds and it worked well.
Thanks

**Comment by magland** [comment]
You're welcome, glad it worked.
