### ISSUE TITLE
Changing tmp directory

### ISSUE THREAD

**Issue by timsainb** [flatironinstitute/mountainsort#6]
Hey all,

I'm currently testing out mountainsort on some larger datasets and am having trouble figuring out where to specify my tmp directory. It defaults to '/tmp/mountainlab/prvbucket'. 

Thanks!

**Comment by jasonechung** [comment]
are you using
> mlconfig
to specify the tmp directory?

**Comment by timsainb** [comment]
Thanks!

**Comment by timsainb** [comment]
The tmp directory appears not to have changed even using mlconfig. Do I need to reinstall to use the new tmp?

```
$ mlconfig
****************************************************
*** Temporary Directory ***
This is the directory where all temporary and intermediate
files are stored. It should be in a location with a lot of
free disk space. You may safely delete the data
periodically, but it is a good idea not to do this during
processing.
**Current temporary path: /mnt/cube/tsainbur/tmp**

...

$ sudo -HE mlp-run mountainsort3.mlp sort --raw=data/B890_test_full.mda --geom=data/geom.csv --firings_out=data/firings_B890.mda --_params=params.json --curate=true
**Using data directory: /tmp/mountainlab/prvbucket**
```

**Comment by magland** [comment]
That surprises me. I am not able to reproduce on my end.

I don't think you should be using "sudo" for processing. 

Could you please run:

mlconfig print

(BTW, there will be a lot of extra info, left over from previous versions -- don't be worried by that)

**Comment by timsainb** [comment]
Figured it out. You were right, it was related to sudo. 

With sudo:
```
$sudo mlconfig print
{
    "general": {
        "max_cache_size_gb": 40,
        "temporary_path": "/mnt/cube/tsainbur/tmp"
    },
```
Without sudo:
```
$mlconfig print
{
    "general": {
        "max_cache_size_gb": 40,
        "temporary_path": "/mnt/cube/tsainbur/tmp"
    },
```
With sudo +HE flags:
```
$sudo -HE mlconfig print
{
    "general": {
        "max_cache_size_gb": 40,
        "temporary_path": "/tmp"
    },
```

Thanks
