### ISSUE TITLE
Clip alignment for low sampling rate recordings [future development question]

### ISSUE THREAD

**Issue by ferchaure** [flatironinstitute/mountainsort#70]
Hi, I was using mountainsort in a few simulations with low sampling rate (24 KHz) and It looks like the method present overclustering generated from the wrong alignment of the spikes. 
Is there an easy way to add interpolation to align better the clips? 
Probably It could help recordings with a higher sampling rate as well.

**Comment by ahbarnett** [comment]
The obvious solution is to upsample your recording by a factor of 2 using some high-order method, and try MS on that.  Generally for 30kHz which is close, we haven't seen erroneous splitting of density peaks associated with different sub-sample alignments (is that what you mean by "overclustering"?)

**Comment by ferchaure** [comment]
Hi Alex, thanks for the quick reply

> The obvious solution is to upsample your recording by a factor of 2 using some high-order method

You are right, probably that is the simplest solution  :+1: 

> Generally for 30kHz which is close, we haven't seen erroneous splitting of density peaks associated with different sub-sample alignments (is that what you mean by "overclustering"?)

Yes, I meant exactly that. I saw small improvements in other methods using interpolation in cases with a low sampling rate, but probably for mountainsort the issue is restricted to single-channel (where a sub-sample misalignment has more weight) and just some type of waveforms :thinking:
