### ISSUE TITLE
Error code 9 in mountainsortalg.ms3

### ISSUE THREAD

**Issue by czawora** [flatironinstitute/mountainsort#8]
When running, mountainsortalg.ms3 processes ~9% of the data and returns with error code 9 and no error message. Anything I can do to debug this more? I am trying to process 96 channels over an hour of recording, a ~20 GB file.

**Comment by jasonechung** [comment]
How much RAM do you have available? Could you share what the console log
displays before the error?

**Comment by czawora** [comment]
55 GB of RAM


![screenshot 2017-12-01 19 29 49](https://user-images.githubusercontent.com/8885571/33509260-06f8061c-d6ce-11e7-87ef-9bb5fca41a03.png)

**Comment by magland** [comment]
I'd need to look at this in more detail. We are working on better options for predicting memory usage, and more memory efficient sorting.
