### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by timsainb** [flatironinstitute/mountainsort#9]
I'm running on mountainsort on Ubuntu 16.04, with 128Gb of RAM and 24 cores. I tried running a ~10hr recording with 32 channels and when I checked on it a few minutes ago, the RAM utilization was at nearly 100%.  The last readout:

```
|mountainsortalg.ms3|            Processed 375.192 MB in 1.491 sec (251.638 MB/sec): Total 46398.7 MB [Read data and add to neighborhood sorters] (46.0434%)...
  |mountainsortalg.ms3|            Processed 125.064 MB in 0.65 sec (192.406 MB/sec): Total 46523.8 MB [Read data and add to neighborhood sorters] (46.1675%)...
  |mountainsortalg.ms3|            Read 500.256 MB in 6.214 sec (80.5047 MB/sec): Total 47024.1 MB [Read data and add to neighborhood sorters]...
  |mountainsortalg.ms3|            Processed 375.192 MB in 58.784 sec (6.38255 MB/sec): Total 46899 MB [Read data and add to neighborhood sorters] (46.5399%)...
  |mountainsortalg.ms3|            Processed 125.064 MB in 1.912 sec (65.41 MB/sec): Total 47024.1 MB [Read data and add to neighborhood sorters] (46.664%)...
```

The params:

 `PARAMS: detect_threshold=3  detect_sign=-1  adjacency_radius=1  consolidate_clusters=true  consolidation_factor=0.9  clip_size=50  detect_interval=10  merge_across_channels=true  fit_stage=true  t1=0  t2=-1
`
I've had some good sorts up to ~2 hours for 32 channel recordings. Any suggestions on how to sort bigger datasets?

**Comment by wysota** [comment]
Hi, how did you measure ram utilization?

**Comment by timsainb** [comment]
htop

**Comment by wysota** [comment]
And which value did you take from htop output?

**Comment by timsainb** [comment]
Mem

**Comment by timsainb** [comment]
After I killed the process the ~120GB of RAM was released
`Mem[|||||||                                                           7.66G/126G]`

**Comment by wysota** [comment]
Mem doesn't tell you much about how much is used by your process. More accurate value is the one in "RES" column for your process.

How large is your recording data file?

**Comment by timsainb** [comment]
The first time I ran it, my filesize was 200GB, which I realized was because I was saving as float64. So I rewrote the mda as int16, making 50GB the new file size. I then tried running it again with the same memory problems: 

`15900 root       20   0  140G  116G   432 D  1.3 92.9  0:26.86 /opt/mountainlab/packages/ms3/ms3.mp ms3.isolation_metrics --firings=/mnt/cube/...`

I think when I killed the process this time it was actually pretty close to finishing:

```
  |ms3.cluster_metrics|            RUNNING ms3.cluster_metrics: /opt/mountainlab/packages/ms3/ms3.mp ms3.cluster_metrics --firings=/mnt/cube/tsainbur/tmp/mountainlab/prvbucket/_mountainprocess/output_firings_out_9db4b230a3 --timeseries=/mnt/cube/tsainbur/tmp/mountainlab/prvbucket/_mountainprocess/output_timeseries_out_58f4abf056 --cluster_metrics_out=/mnt/cube/tsainbur/tmp/mountainlab/prvbucket/_mountainprocess/output_cluster_metrics_out_cc6a78f1d5 --samplerate=20000 --_tempdir=/mnt/cube/tsainbur/tmp/mountainlab/tmp_short_term/tempdir_M2GNEN66TY
  |ms3.isolation_metrics|          Computing cluster metrics...
  |ms3.cluster_metrics|            Process completed successfully: ms3.cluster_metrics (Elapsed: 12.694 sec)
  |ms3.cluster_metrics|            making prv file: /mnt/cube/tsainbur/tmp/mountainlab/prvbucket/_mountainprocess/output_cluster_metrics_out_cc6a78f1d5.prv
  |ms3.cluster_metrics|            making prv file: /mnt/cube/tsainbur/tmp/mountainlab/prvbucket/_mountainprocess/output_console_out_cc6a78f1d5.prv
```

**Comment by timsainb** [comment]
Tried restarting the sort, picking up where the killed process left off. I got here:

`|ms3.isolation_metrics|          Starting p_isolation_metrics
  |ms3.isolation_metrics|          Computing cluster metrics...`

Before RES again jumped up to 120G.

**Comment by magland** [comment]
How many CPU cores? Wondering how many threads are running, because that will affect memory usage. There are things we can do to reduce the memory consumption...

**Comment by timsainb** [comment]
24. Is there any way to estimate how much RAM is going to be used given
dataset size and number of cores?

Also - where do I define #of cores to use?

**Comment by magland** [comment]
I am now working on a system where it estimates the amt of RAM needed before running it.

The easiest way is to use set the OMP_NUM_THREADS environment variable. For example, in your terminal:

export OMP_NUM_THREADS=8

That should reduce the memory usage. I'll try to follow up with info on the RAM estimate.

(If you don't here from me this week, please follow up)

**Comment by timsainb** [comment]
Awesome! And yes, dropping OMP_NUM_THREADS down to 8 worked.

**Comment by magland** [comment]
Great! I'm aiming to have the RAM estimation system working by the end of the week. If not, and you think of it, please do a favor and re-open this issue.
